create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists private.notes_admin_emails (
  email text primary key,
  created_at timestamptz not null default now()
);

alter table private.notes_admin_emails enable row level security;

create table if not exists public.notes_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.page_notes (
  id bigint generated by default as identity primary key,
  page_key text not null,
  title text not null check (char_length(title) between 1 and 120),
  body text not null default '' check (char_length(body) <= 800),
  status text not null default 'open' check (status in ('open', 'waiting', 'completed')),
  sort_order integer not null default 0,
  author_id uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists page_notes_page_title_idx
  on public.page_notes(page_key, title);

create index if not exists page_notes_page_order_idx
  on public.page_notes(page_key, sort_order, created_at);

create or replace function public.notes_set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists page_notes_set_updated_at on public.page_notes;
create trigger page_notes_set_updated_at
before update on public.page_notes
for each row execute function public.notes_set_updated_at();

create or replace function public.is_notes_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.notes_admins
    where user_id = (select auth.uid())
  );
$$;

create or replace function public.claim_notes_admin()
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  claim_email text := lower((select auth.jwt()->>'email'));
begin
  if (select auth.uid()) is null then
    return false;
  end if;

  if exists (
    select 1 from private.notes_admin_emails
    where email = claim_email
  ) then
    insert into public.notes_admins(user_id)
    values ((select auth.uid()))
    on conflict (user_id) do nothing;
    return true;
  end if;

  return false;
end;
$$;

alter table public.notes_admins enable row level security;
alter table public.page_notes enable row level security;

drop policy if exists "Users can see their notes admin record" on public.notes_admins;
create policy "Users can see their notes admin record"
on public.notes_admins for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Anyone can read page notes" on public.page_notes;
create policy "Anyone can read page notes"
on public.page_notes for select
to anon, authenticated
using (true);

drop policy if exists "Notes admins can insert page notes" on public.page_notes;
create policy "Notes admins can insert page notes"
on public.page_notes for insert
to authenticated
with check ((select public.is_notes_admin()));

drop policy if exists "Notes admins can update page notes" on public.page_notes;
create policy "Notes admins can update page notes"
on public.page_notes for update
to authenticated
using ((select public.is_notes_admin()))
with check ((select public.is_notes_admin()));

drop policy if exists "Notes admins can delete page notes" on public.page_notes;
create policy "Notes admins can delete page notes"
on public.page_notes for delete
to authenticated
using ((select public.is_notes_admin()));

revoke all on public.notes_admins from anon, authenticated;
grant select on public.notes_admins to authenticated;
grant select on public.page_notes to anon, authenticated;
grant insert, update, delete on public.page_notes to authenticated;
grant usage, select on sequence public.page_notes_id_seq to authenticated;
revoke all on function public.is_notes_admin() from public;
revoke all on function public.claim_notes_admin() from public;
grant execute on function public.is_notes_admin() to authenticated;
grant execute on function public.claim_notes_admin() to authenticated;

insert into public.page_notes(page_key, title, body, status, sort_order)
values
  ('characters', 'Improve faction names / amount', '', 'open', 0),
  ('characters', 'Create surnames', '', 'open', 1),
  ('story', 'Replace placeholder chapters', 'Swap the temporary drafts for final story installments when they are provided.', 'open', 0),
  ('music', 'Replace placeholder tracks', 'Add final titles, credits, artwork, and audio when music files are available.', 'open', 0),
  ('character', 'Replace mock profile data', 'Confirm the personal timeline and each profile section when final character material is available.', 'open', 0),
  ('duchy', 'Add city images', 'Replace the Rennel, Vilen, and Turon placeholders when approved city art is available.', 'waiting', 0)
on conflict do nothing;

-- Add the owner email only in the Supabase SQL editor. Do not commit it here.
-- insert into private.notes_admin_emails(email) values (lower('owner@example.com'));
