window.MAGIARCHY_STORY_PHASES = [
  { id: 'vanishing-point', number: '01', label: 'First disappearances', title: 'Vanishing Point', description: 'People disappear inside an enormous park in Vilen. The search parties sent after them vanish too, turning an isolated mystery into a growing crisis.' },
  { id: 'the-quarantine', number: '02', label: 'Blind containment', title: 'The Quarantine', description: 'The government seals the park and deploys the army. The Spill is kept from the public, but nobody in command understands what they are containing.' },
  { id: 'divided-attention', number: '03', label: 'Manufactured strife', title: 'Divided Attention', description: 'Pressure from Magiarchs abroad and several churches reaches Fionn through political conflict inside Narvea and MSF, keeping him occupied when the Spill needs its Magiarch.' },
  { id: 'the-takeover', number: '04', label: 'Unresolved assassination', title: 'The Takeover', description: 'Fionn is assassinated. The ultimate author and full coalition remain unresolved, but Helena plays a major role before using the opening to seize MSF and frame Lynleit for his death.' },
  { id: 'unknowing-convergence', number: '05', label: 'Political mask', title: 'Unknowing Convergence', description: 'Government agents, police, private investigators, churches, and independent figures pursue what appears to be a political conspiracy. Kyrien enters that hidden conflict after an attempt on a Magus politician connected to his father\'s death.' },
  { id: 'clear-her-name', number: '06', label: 'Return from exile', title: 'Clear Her Name', description: 'Lynleit works from outside the system to expose Helena, restore her name, and separate the visible MSF takeover from the deeper forces that arranged Fionn\'s downfall.' },
  { id: 'the-real-mission', number: '07', label: 'A smaller MSF', title: 'The Real Mission', description: 'The Spill cannot be fully contained. MSF contracts into a smaller, mainly Magi-focused task force whose members must now juggle magical threats and ordinary intelligence work.' },
  { id: 'after-the-spill', number: '08', label: 'Permanent containment', title: 'The Unfinished Spill', description: 'The political struggle for MSF is settled, but the Spill remains. The agency and everyone changed by the crisis must rebuild around a threat that has become a permanent mandate.' },
  { id: 'lynleit-disappears', number: '09', label: 'Protected absence', title: 'Lynleit Disappears', description: 'Lynleit vanishes to conceal her pregnancy, keep the child beyond the conflict\'s reach, recover, and investigate the Spill\'s origins with wiser advisers. Kyrien is left in charge of MSF.' },
  { id: 'kyriens-burden', number: '10', label: 'A non-Magus director', title: 'Kyrien\'s Burden', description: 'Kyrien inherits an agency built to confront magic without being a Magus himself. He survives leadership by peaking the intelligence-operative side of MSF: subterfuge, counterintelligence, evasion, firearms, field survival, and contingency planning.' },
  { id: 'the-return', number: '11', label: 'Years later', title: 'The Return', description: 'After recovering and placing her son with a reliable distant relative, Lynleit begins appearing near MSF missions without announcing her return. Only a few notice her, sometimes Kyrien, and her unexplained activity can make her look like a culprit rather than an ally.' }
];
