window.MAGIARCHY_STORY_ARCS = [
  { id: 'arc-1', number: 'ARC 1', title: 'Main story', description: 'The central story and its first major life period. Its internal phases may cover several years.' },
  { id: 'arc-2', number: 'ARC 2', title: 'After the main story', description: 'A sequel life period shaped by Lynleit\'s absence, Kyrien\'s direction of MSF, and the consequences carried forward from Arc 1.' }
];

window.MAGIARCHY_STORY_PHASES = [
  { id: 'vanishing-point', arc: 'arc-1', arcLabel: 'Arc 1', number: '01', label: 'First disappearances', title: 'Vanishing Point', description: 'The first person to disappear independently causes the Spill, though his identity and significance remain concealed for most of the story. Holumns cause the disappearances that follow. Hidden factions later recognize and exploit a crisis they did not create.' },
  { id: 'the-quarantine', arc: 'arc-1', arcLabel: 'Arc 1', number: '02', label: 'Public danger, unknown cause', title: 'The Quarantine', description: 'The disappearances are too widespread to conceal. Police close the park, then the government seals it even from them and deploys specially equipped paramilitary units without understanding what they are containing.' },
  { id: 'the-hidden-wager', arc: 'arc-1', arcLabel: 'Arc 1', number: '03', label: 'An intuitive warning', title: 'The Hidden Wager', description: 'Within the first few chapters, Lynleit senses danger approaching before she can prove its shape. She secretly recruits Kyrien as an unknown ally against Helena, accepts the personal risk, and tells only Felix and Reiner while keeping even Fionn uninformed.' },
  { id: 'unknowing-convergence', arc: 'arc-1', arcLabel: 'Arc 1', number: '04', label: 'Political mask', title: 'Unknowing Convergence', description: 'Government agents, police, private investigators, churches, and independent figures pursue what appears to be a political conspiracy. A covert inspection of apparently unmanned river shipments finds empty contraband boats and the Drowned Choir. Kyrien alone witnesses Lynleit walk on water and protects the forbidden secret.' },
  { id: 'divided-attention', arc: 'arc-1', arcLabel: 'Arc 1', number: '05', label: 'Foreign and domestic pressure', title: 'Divided Attention', description: 'Pressure from Magiarchs abroad and several churches keeps Fionn occupied when the Spill needs its Magiarch. Father Mikhail\'s mission in Cardiff draws Lynleit away from Narvea while Kyrien enters the Magi Academy in her place to protect Myka.' },
  { id: 'the-takeover', arc: 'arc-1', arcLabel: 'Arc 1', number: '06', label: 'Intuition vindicated', title: 'The Takeover', description: 'Much later, several incompatible agendas converge into Fionn\'s assassination without one actor controlling the whole outcome. Helena knowingly opens one door, then seizes MSF and frames Lynleit without understanding everything that followed her choice.' },
  { id: 'clear-her-name', arc: 'arc-1', arcLabel: 'Arc 1', number: '07', label: 'Fugitive counteroffensive', title: 'Clear Her Name', description: 'After Fionn\'s murder, Helena frames Lynleit and directs a hunt for her arrest. Lynleit discovers Fionn\'s leviathan-hide coat during the middle of Arc 1, then begins a slow campaign to reclaim MSF while the hunt continues.' },
  { id: 'the-real-mission', arc: 'arc-1', arcLabel: 'Arc 1', number: '08', label: 'A smaller MSF', title: 'The Real Mission', description: 'The Spill cannot be fully contained. MSF contracts into a smaller, mainly Magi-focused task force whose members must now juggle magical threats and ordinary intelligence work.' },
  { id: 'after-the-spill', arc: 'arc-1', arcLabel: 'Arc 1', number: '09', label: 'Permanent containment', title: 'The Unfinished Spill', description: 'The political struggle for MSF is settled, but the Spill remains. The agency and everyone changed by the crisis must rebuild around a threat that has become a permanent mandate.' },
  { id: 'lynleit-disappears', arc: 'arc-1', arcLabel: 'Arc 1', number: '10', label: 'Protected absence', title: 'Lynleit Disappears', description: 'After a story-long accumulation of functional and non-sexual intimacy, Lynleit and Kyrien cross a private threshold at the end of Arc 1. Lynleit disappears near the transition into the next life period, leaving Kyrien in charge of MSF.' },
  { id: 'kyriens-burden', arc: 'arc-2', arcLabel: 'Arc 2', number: '11', label: 'A non-Magus director', title: 'Kyrien\'s Burden', description: 'At the opening of Arc 2, Kyrien directs an agency built to confront magic without being a Magus himself. The circumstances surrounding Lynleit\'s absence allow the reader to infer her pregnancy without a direct explanation or shown realization.' },
  { id: 'the-return', arc: 'arc-2', arcLabel: 'Arc 2', number: '12', label: 'Years later', title: 'The Return', description: 'After recovering and placing her son with a reliable distant relative, Lynleit begins appearing near MSF missions without announcing her return. Only a few notice her, sometimes Kyrien, and her unexplained activity can make her appear responsible for the danger.' }
];
