window.MAGIARCHY_STORY_PHASES = [
  { id: 'vanishing-point', number: '01', label: 'First disappearances', title: 'Vanishing Point', description: 'The first person to disappear independently causes the Spill, though his identity and significance remain concealed for most of the story. Holumns cause the disappearances that follow. Hidden factions later recognize and exploit a crisis they did not create.' },
  { id: 'the-quarantine', number: '02', label: 'Public danger, unknown cause', title: 'The Quarantine', description: 'The disappearances are too widespread to conceal. Police close the park, then the government seals it even from them and deploys specially equipped paramilitary units without understanding what they are containing.' },
  { id: 'the-hidden-wager', number: '03', label: 'An intuitive warning', title: 'The Hidden Wager', description: 'Within the first few chapters, Lynleit senses danger approaching before she can prove its shape. She secretly recruits Kyrien as an unknown ally against Helena, accepts the personal risk, and tells only Felix and Reiner while keeping even Fionn uninformed.' },
  { id: 'unknowing-convergence', number: '04', label: 'Political mask', title: 'Unknowing Convergence', description: 'Government agents, police, private investigators, churches, and independent figures pursue what appears to be a political conspiracy. During the failed river operation, Kyrien silently protects Lynleit\'s water-walking secret, creating the first trigger in a slow intimacy built through functional trust.' },
  { id: 'divided-attention', number: '05', label: 'Manufactured strife', title: 'Divided Attention', description: 'Pressure from Magiarchs abroad and several churches reaches Fionn through political conflict inside Narvea and MSF, keeping him occupied when the Spill needs its Magiarch.' },
  { id: 'the-takeover', number: '06', label: 'Intuition vindicated', title: 'The Takeover', description: 'Much later, several incompatible agendas converge into Fionn\'s assassination without one actor controlling the whole outcome. Helena knowingly opens one door, then seizes MSF and frames Lynleit without understanding everything that followed her choice.' },
  { id: 'clear-her-name', number: '07', label: 'Fugitive counteroffensive', title: 'Clear Her Name', description: 'After Fionn\'s murder, Helena frames Lynleit and directs a hunt for her arrest. Lynleit exhausts her available resources to escape into Kyrien\'s hotel-room hideout. He later helps her establish contact with Felix and Reiner, beginning a slow campaign to reclaim MSF while the hunt continues.' },
  { id: 'the-real-mission', number: '08', label: 'A smaller MSF', title: 'The Real Mission', description: 'The Spill cannot be fully contained. MSF contracts into a smaller, mainly Magi-focused task force whose members must now juggle magical threats and ordinary intelligence work.' },
  { id: 'after-the-spill', number: '09', label: 'Permanent containment', title: 'The Unfinished Spill', description: 'The political struggle for MSF is settled, but the Spill remains. The agency and everyone changed by the crisis must rebuild around a threat that has become a permanent mandate.' },
  { id: 'lynleit-disappears', number: '10', label: 'Protected absence', title: 'Lynleit Disappears', description: 'After a story-long accumulation of functional and non-sexual intimacy, Lynleit and Kyrien finally have sex at the end of the first arc. Pregnancy and disappearance follow. She vanishes to keep the child beyond the conflict\'s reach, recover, and investigate the Spill\'s origins with wiser advisers, leaving Kyrien in charge of MSF.' },
  { id: 'kyriens-burden', number: '11', label: 'A non-Magus director', title: 'Kyrien\'s Burden', description: 'Kyrien inherits an agency built to confront magic without being a Magus himself. He survives leadership by peaking the intelligence-operative side of MSF: subterfuge, counterintelligence, evasion, firearms, field survival, and contingency planning.' },
  { id: 'the-return', number: '12', label: 'Years later', title: 'The Return', description: 'After recovering and placing her son with a reliable distant relative, Lynleit begins appearing near MSF missions without announcing her return. Only a few notice her, sometimes Kyrien, and her unexplained activity can make her appear responsible for the danger.' }
];
